import { LOCAL_UI_RUNTIME } from "./local-ui-runtime.js";
import { LOCAL_UI_STYLE } from "./local-ui-style.js";

const PRODUCT_FAVICON = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='16' fill='%233157d5'/%3E%3Ccircle cx='27' cy='27' r='13' fill='none' stroke='white' stroke-width='6'/%3E%3Cpath d='m37 37 12 12' fill='none' stroke='white' stroke-linecap='round' stroke-width='6'/%3E%3Cpath d='m21 27 5 5 9-11' fill='none' stroke='white' stroke-linecap='round' stroke-linejoin='round' stroke-width='4'/%3E%3C/svg%3E";

export function embedLocalReport(html: string): string {
  const style = `<style id="seo-audit-embed-style">header,.report-nav{display:none!important}main{width:min(1600px,calc(100% - 24px));margin:16px auto 32px}.analytics{margin-bottom:12px}</style>`;
  return html.replace("</head>", `${style}</head>`);
}

const PAGE_TEMPLATE = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="${PRODUCT_FAVICON}" type="image/svg+xml"><title>SEO Crawl Audit</title><style>
${LOCAL_UI_STYLE}
</style></head><body><main><div class="brand"><div class="mark">✓</div><div><h1>SEO Crawl Audit</h1><div class="muted">Free, local-first site crawler</div></div></div><section class="panel"><div class="form"><label><span>Website URL</span><input id="url" type="url" placeholder="https://example.com/" required></label><label><span>Scan profile</span><select id="profile"><option value="quick">Quick · 100</option><option value="standard">Standard · 1,000</option><option value="full">Full sitemap</option><option value="custom">Custom</option></select></label><label id="pagesLabel" hidden><span>Pages</span><input id="pages" type="number" min="1" max="50000" value="100"></label><label><span>Concurrency</span><input id="concurrency" type="number" min="1" max="20" value="5"></label><label><span>Delay, ms</span><input id="delay" type="number" min="0" max="60000" value="100"></label><label><span>Rendering</span><select id="render"><option value="http">Fast HTTP</option><option value="playwright">Playwright (optional)</option></select></label></div><div class="actions"><button id="start">Start SEO scan</button><button id="cancel" class="secondary" disabled>Stop safely</button></div><div class="progress"><i id="bar"></i></div><div><span class="status" id="status">Idle</span> <span class="muted" id="message">Ready to scan locally.</span></div><div class="muted" id="current"></div><div class="stats"><div class="stat"><strong id="completed">0</strong>Pages</div><div class="stat"><strong id="errors">0</strong>Errors</div><div class="stat"><strong id="warnings">0</strong>Warnings</div><div class="stat"><strong id="info">0</strong>Info</div></div><div class="links"><a id="report" href="/report" target="_blank" hidden>Open full report in a new tab</a></div></section><section class="panel"><h2>Site Metrics</h2><p class="muted">Optional public Google and RDAP data. Uses the latest local snapshot and does not crawl pages again.</p><div class="form"><label><span>Google site: estimate (optional)</span><input id="googleEstimate" type="number" min="1" step="1" placeholder="e.g. 19300"></label></div><div class="actions"><button id="updateMetrics" class="secondary">Update public metrics</button><a id="googleCheck" href="https://www.google.com/" target="_blank" rel="noopener">Check site: query in Google</a></div><div id="metricsMessage" class="muted">Run an SEO scan first.</div></section><section id="reportPanel" class="panel report-preview" hidden><div class="report-preview-header"><div><h2>Latest local report</h2><div class="muted">Compact overview preview</div></div><a href="/report" target="_blank" rel="noopener">Open full report</a></div><iframe id="reportFrame" class="report-frame" title="Compact SEO Crawl Audit report"></iframe></section></main><script>
${LOCAL_UI_RUNTIME}
</script></body></html>`;


export const LOCAL_UI_PAGE = PAGE_TEMPLATE;
